language: perl
install:
  - cpanm -n Clustericious::Client
  - cpanm -n Log::Log4perl
  - cpanm -n Log::Log4perl::CommandLine
  - cpanm -n Term::Prompt
script: HARNESS_IS_VERBOSE=1 prove -lvr t xt
perl:
  - "5.19"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
